require File.expand_path("#{File.dirname(__FILE__)}/lib/aws")
Dir.glob('lib/task/*.rake').each { |r| import r }

QA = '[REPLACE].compute-1.amazonaws.com'
PROD = '[REPLACE].compute-1.amazonaws.com'

task :default do; sh "rake -T"; end

desc "QA: ssh"
task :sshqa, :cmd do |t, args|
    task('ec2:ssh').invoke(QA, args[:cmd])
end

desc "PROD: ssh"
task :sshprod, :cmd do |t, args|
    task('ec2:ssh').invoke(PROD, args[:cmd])
end

